### ISSUE TITLE
Using roundcube 1.2.0 reply/forward with custom_from enabled does not send message

### ISSUE THREAD

**Issue by daviessm** [r3c/custom_from#17]
After I updated to Roundcube 1.2.0 I have been unable to reply to or forward any messages with the latest version of custom_from enabled. Once I disable the plugin, I can once again reply to and forward messages.

The compose window displays as expected but upon clicking Send the message "Sending message..." is displayed at the top of the window and never leaves. The email is not sent and I have to manually navigate back to the main Roundcube page to continue the session.

**Comment by r3c** [comment]
Hello,

are you sure you're running latest version of custom_from? Commits added very recently added a few changes required to support Roundcube 1.2.0.

If you still have issue with last version, please provide as much details as possible (e.g. content of Roundcube error logs, anything that could appear in the developer console, etc.) so I can have a starting point for investigation.

Thanks.

**Comment by daviessm** [comment]
You're right, it's not related to custom_from. I've tried disabling the plugin again and now get the error with it disabled too. For the record it was this:

`app.min.js?s=1466194882:175 POST https://webmail.example.com/?_task=mail&_unlock=loading1467029957028&_lang=en_GB&_framed=1 net::ERR_SPDY_PROTOCOL_ERROR`
