### ISSUE TITLE
Toggle button is in wrong state on page load

### ISSUE THREAD

**Issue by MattDahEpic** [r3c/custom_from#23]
I'm using a freshly pulled version of this repository and Roundcube 1.4.11.

When composing a new email the From field is in the identity list mode but the button is in the "red x" form.
![image](https://user-images.githubusercontent.com/7366951/116747874-c9875480-a9bb-11eb-932f-90c3235891df.png)
After clicking the button once it remains in the "red x" form but the field switches to the text input (as expected).
![image](https://user-images.githubusercontent.com/7366951/116747988-f176b800-a9bb-11eb-80a3-3174517527d4.png)
Clicking the button once more returns the field to the identity list mode and changes the button to how I would expect, the "text icon."
![image](https://user-images.githubusercontent.com/7366951/116748055-0fdcb380-a9bc-11eb-92f5-8a9081784a58.png)

**Comment by r3c** [comment]
Hello @MattDahEpic, you're right the initial state was wrong when compositing an e-mail using a sender address from your list (not a custom one). It should be better now, let me know if you still have an issue 🙂
